## Select image from https://hub.docker.com/_/php/
image: ubuntu:16.10

services:
- mysql:8
- php:7

variables:
  # Configure mysql service (https://hub.docker.com/_/mysql/)
  MYSQL_DATABASE: inc
  MYSQL_ROOT_PASSWORD: pass

before_script:
- bash install.sh
- perl util/parameters_load.pl

# local variables
#  https://dev.mysql.com/doc/refman/5.7/en/environment-variables.html

test:
  image: mysql
  image: php
  script:
  - export MYSQL_PWD=$MYSQL_ROOT_PASSWORD;
  - export MYSQL_HOST="mysql";
  - echo "SELECT 'OK';" | mysql --user=root "$MYSQL_DATABASE"
  - bash test.sh


