## Select image from https://hub.docker.com/_/php/
image: ubuntu:16.10

services:
- mysql

variables:
  # Configure mysql service (https://hub.docker.com/_/mysql/)
  MYSQL_DATABASE: inc
  MYSQL_ROOT_PASSWORD: pass

before_script:
- bash install.sh
- perl util/parameters_load.pl
- curl -L "https://storage.googleapis.com/google-code-archive-downloads/v2/code.google.com/shunit2/shunit2-2.1.6.tgz" | tar zx

# local variables
#  https://dev.mysql.com/doc/refman/5.7/en/environment-variables.html

test:
  image: mysql
  script:
  - export MYSQL_PWD=$MYSQL_ROOT_PASSWORD;
  - export MYSQL_HOST="mysql";
  - echo "SELECT 'OK';" | mysql --user=root "$MYSQL_DATABASE"
  - bash test.sh
  - bash equality_test.sh
  - bash inc.bash


