# Select image from https://hub.docker.com/_/php/
image: ubuntu:16.10

#variables:
#  MYSQL_ROOT_PASSWORD: pass
#  MYSQL_DATABASE: inc
#
#services:
#- mysql:8

before_script:
- echo "\n\n\nBEFORE INSTALL\n\n\n"
- bash install.sh
- echo "\n\n\nBEFORE SOCK\n\n\n"
- /etc/init.d/mysql stop
- mysqld_safe --skip-grant-tables &
- echo "\n\n\nBEFORE RESET PRIVILEGES\n\n\n"
- mysql -u root < util/reset_privileges.sql
- sudo /etc/init.d/mysql start
- echo "\n\n\nBEFORE PARAMS\n\n\n"
- mysql -u root < inc/def.sql;
- perl util/parameters_load.pl
- curl -L "https://storage.googleapis.com/google-code-archive-downloads/v2/code.google.com/shunit2/shunit2-2.1.6.tgz" | tar zx

test:
  script:
  - bash equality_test.sh
  - bash inc.bash

