## Select image from https://hub.docker.com/_/php/
image: ubuntu:16.10

services:
- mysql:8
- php:7

variables:
  # Configure mysql service (https://hub.docker.com/_/mysql/)
  MYSQL_DATABASE: inc
  MYSQL_ROOT_PASSWORD: pass

before_script:
#- add-apt-repository ppa:ondrej/php
- apt-get update -y
- php -v
- apt-get install -y python
- apt-get install -y default-jdk
- apt-get install -y g++
- apt-get install -y mono-mcs
- apt-get install -y gfortran
- apt-get install -y fp-compiler
- apt-get install -y r-base
- apt-get install -y nodejs-legacy
- apt-get install -y ruby
- bash install.sh
- perl util/parameters_load.pl
- curl -L "https://storage.googleapis.com/google-code-archive-downloads/v2/code.google.com/shunit2/shunit2-2.1.6.tgz" | tar zx

# local variables
#  https://dev.mysql.com/doc/refman/5.7/en/environment-variables.html

test:
  image: mysql
  image: php
  script:
  - export MYSQL_PWD=$MYSQL_ROOT_PASSWORD;
  - export MYSQL_HOST="mysql";
  - echo "SELECT 'OK';" | mysql --user=root "$MYSQL_DATABASE"
  - bash test.sh


